spring:
  application:
    name: CustomerService

  datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5432/customers_db

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

