spring:
  application:
    name: CustomerService

  datasource:
    username: Kirill
    password: 191919
    url: jdbc:postgresql://localhost:5432/customers_db

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

